import type { Metadata } from "next";
import "./globals.css";
import WagmiProviderWrapper from "@/providers/WagmiProvider";
import { Toaster } from "@/components/ui/toaster";
import Navigation from "@/components/navigation/Navigation";
import { Provider } from "@/components/ui/provider";
import Footer from "@/components/footer/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`antialiased`}
      >
        <WagmiProviderWrapper>
          <Provider>
            <Navigation />
            <Toaster />
            {children}
            <Footer />
          </Provider>
        </WagmiProviderWrapper>
      </body>
    </html>
  );
}
